#Config files
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"


#resource defaults
local-cores: 1
restart-times: 3
max-jobs-per-second: 1
max-status-checks-per-second: 1

latency-wait: 60
use-conda: True
conda-frontend: "mamba"
conda-cleanup-pkgs: "cache"




