restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
use-conda: True
use-singularity: True
singularity-args: "--bind /scratch --bind /home --bind /project"
conda-frontend: "mamba"
conda-cleanup-pkgs: "cache"




