# Sample IDs as list
samples: "/scratch/henrygeo/SamplesPlantID.txt"


# Path prefixes for results output by this pipeline
results_prefix: /scratch/henrygeo/RNAproject/Results
temp_dir: /scratch/henrygeo/scratch/tmp